import Foundation

/// A "where you stopped" pulse generated by Track-1 D3 `WhereStoppedDeriver`.
/// Sourced from M014 `where_stopped_log` table via
/// `DerivedInsights.recentWhereStopped(limit:)`.
///
/// Track-9 T7 — adds Optional anchor file resolution (deriver-side LEFT JOIN
/// against `events.payload_json.doc_path/.line`) and `recentLastCommit`
/// (Reader-side composition per Path B lock). All new fields defaulted nil
/// for backward-compat at existing call sites.
public struct WhereStoppedSnapshot: Equatable, Sendable {
    public let id: Int64
    public let generatedAtMs: Int64
    public let anchorEventId: Int64?
    public let excerpt: String
    public let wipSignals: [String]
    public let anchorFilePath: String?
    public let anchorLine: Int?
    public let recentLastCommit: RecentCommitSnapshot?
    /// Track-10 T2 — bundle ID of the anchor event's foreground app (read from
    /// `events.bundle_id` via the existing reader-side LEFT JOIN). Powers the
    /// RESUME hero "Resume" CTA — target app to relaunch when the user clicks.
    /// `nil` ↔ anchor missing / orphaned (anchor event swept) / pre-T2 row.
    public let anchorBundleID: String?

    public init(
        id: Int64,
        generatedAtMs: Int64,
        anchorEventId: Int64?,
        excerpt: String,
        wipSignals: [String],
        anchorFilePath: String? = nil,
        anchorLine: Int? = nil,
        recentLastCommit: RecentCommitSnapshot? = nil,
        anchorBundleID: String? = nil
    ) {
        self.id = id
        self.generatedAtMs = generatedAtMs
        self.anchorEventId = anchorEventId
        self.excerpt = excerpt
        self.wipSignals = wipSignals
        self.anchorFilePath = anchorFilePath
        self.anchorLine = anchorLine
        self.recentLastCommit = recentLastCommit
        self.anchorBundleID = anchorBundleID
    }
}

extension WhereStoppedSnapshot: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(generatedAtMs)
    }
}
