import Foundation

/// A "where you stopped" pulse generated by Track-1 D3 `WhereStoppedDeriver`.
/// Sourced from M014 `where_stopped_log` table via
/// `DerivedInsights.recentWhereStopped(limit:)`.
public struct WhereStoppedSnapshot: Equatable, Hashable, Sendable {
    public let id: Int64
    public let generatedAtMs: Int64
    public let anchorEventId: Int64?
    public let excerpt: String
    public let wipSignals: [String]

    public init(
        id: Int64,
        generatedAtMs: Int64,
        anchorEventId: Int64?,
        excerpt: String,
        wipSignals: [String]
    ) {
        self.id = id
        self.generatedAtMs = generatedAtMs
        self.anchorEventId = anchorEventId
        self.excerpt = excerpt
        self.wipSignals = wipSignals
    }
}
